# Generated by Django 5.1.2 on 2024-10-13 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_password_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='real_estate',
            name='state',
            field=models.CharField(default='disponible', max_length=255),
        ),
    ]
