# Generated by Django 5.1.2 on 2024-10-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_real_estate_img1_alter_real_estate_img2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='real_estate',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='real_estate',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='real_estate',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='real_estate',
            name='img4',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
