# Generated by Django 5.1.2 on 2024-10-14 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_real_estate_img1_alter_real_estate_img2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='real_estate',
            name='addres',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.address'),
        ),
        migrations.AlterField(
            model_name='real_estate',
            name='ow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.owner'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='real_e',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.real_estate'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='ten',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.tenant'),
        ),
    ]
