# Generated by Django 5.1.2 on 2024-10-14 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_real_estate_addres_alter_real_estate_ow_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rental',
            old_name='ten',
            new_name='tenant',
        ),
    ]
