# Generated by Django 5.1.2 on 2024-10-14 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_ten_rental_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
