# Generated by Django 5.1.2 on 2024-10-15 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_rental_real_e_alter_rental_superentity_ptr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='real_estate',
            name='img5',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='real_estate',
            name='img6',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='real_estate',
            name='img7',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='real_estate',
            name='img8',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
