# Generated by Django 5.1.2 on 2024-10-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_real_estate_img5_real_estate_img6_real_estate_img7_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='municipality',
            field=models.CharField(default='Sébikotane', max_length=255),
        ),
        migrations.AlterField(
            model_name='address',
            name='neighborhood',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=255),
        ),
    ]
